# Generated by Django 3.2.9 on 2021-11-07 00:48

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
